version: '3.3'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: red_social
    volumes:
      - ./mysql_data:/var/lib/mysql:rw
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    expose:
      - 80
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
